### ISSUE TITLE
Oh no!

### ISSUE THREAD

**Issue by Iamtheoldman** [wp-innovator/innovator-ai#6]
Fatal error: Uncaught Error: Failed opening required '/nas/content/live/txmedcoverage/wp-content/plugins/innovator-ai-main/vendor/autoload.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/txmedcoverage/wp-content/plugins/innovator-ai-main/innovator-ai.php:56 Stack trace: #0 /nas/content/live/txmedcoverage/wp-content/plugins/innovator-ai-main/innovator-ai.php(83): Innovator_Ai->__construct() #1 /nas/content/live/txmedcoverage/wp-content/plugins/innovator-ai-main/innovator-ai.php(330): Innovator_Ai::init() #2 /nas/content/live/txmedcoverage/wp-content/plugins/innovator-ai-main/innovator-ai.php(338): innovator_ai() #3 /nas/content/live/txmedcoverage/wp-admin/includes/plugin.php(2314): include_once('/nas/content/li...') #4 /nas/content/live/txmedcoverage/wp-admin/plugins.php(192): plugin_sandbox_scrape('innovator-ai-ma...') #5 {main} thrown in /nas/content/live/txmedcoverage/wp-content/plugins/innovator-ai-main/innovator-ai.php on line 56

**Comment by ManiruzzamanAkash** [comment]
Hi, Could you help me to generate this issue? - how do you get the zip file to upload plugin?

1) Are you getting it from WordPress plugin directory? Or
2) You are taking from Github?

**Comment by ManiruzzamanAkash** [comment]
As this is not reproducable, or may be you've tried from Github.

Please you're suggested to follow two approach - 
1) Install plugin from WordPress plugin directory - https://wordpress.org/plugins/innovator-ai/

or,

2) Get the latest release from this tag - https://github.com/wp-innovator/innovator-ai/releases/tag/v1.1.0

**Comment by Iamtheoldman** [comment]
i did just that and got the error again
